name: CI/CD Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Build the Java app
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t spring_rest:latest .

      # Step 6: Tag Docker image for Docker Hub
      - name: Tag Docker image
        run: docker tag spring_rest:latest ${{ secrets.DOCKER_USERNAME }}/spring_rest:latest

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring_rest:latest
